static const FFCodec * const codec_list[] = {
    &ff_h263_decoder,
    &ff_h264_decoder,
    &ff_mjpeg_decoder,
    &ff_mpeg4_decoder,
    &ff_theora_decoder,
    &ff_vp3_decoder,
    &ff_vp8_decoder,
    &ff_vp9_decoder,
    &ff_aac_decoder,
    &ff_aac_latm_decoder,
    &ff_flac_decoder,
    &ff_mp3_decoder,
    &ff_opus_decoder,
    &ff_vorbis_decoder,
    &ff_pcm_s16le_decoder,
    &ff_pcm_u8_decoder,
    NULL };
