/// Un fil d'execution utilisateur.
pub struct Task {
    pub tid: u32,
    pub process: Arc<Process>,
    pub state: TaskState,
    pub priorite: Priorite,
    pub affinity_mask: u64,
    pub runq_cpu: u8,
    pub last_cpu: u8,
    pub on_cpu: i8,
    switching_out: bool,
    pub last_migration_ns: u64,
    pub recent_runtime_ns: u64,
    pub slice_start_ns: u64,
    /// Instant ou la tache est devenue runnable sans encore avoir de CPU.
    /// Zero signifie "pas en file". Sert a la latence wake/ready-to-run NG.
    pub ready_since_ns: u64,
    pub last_account_ns: u64,
    pub user_cpu_ns: u64,
    pub kernel_cpu_ns: u64,
    pub cpu_ns: [u64; MAX_CPUS],
    pub in_kernel: bool,
    pub context_switches: u64,
    pub migrations: u64,
    pub frame: TrapFrame,
    pub ctx: Context,
    kstack: Vec<u8>,
    pub kstack_top: u64,
    fpu: Vec<u8>,
    fpu_area: u64,
    pub fs_base: u64,
    pub clear_child_tid: u64,
    pub futex_key: u64,
    pub wait_queue_key: usize,
    pub wake_deadline_ns: u64,
    pub waiting_for_child: bool,
    pub fresh: bool,
    pub ticks_cpu: u64,
    pub noyau: bool,
    entree_noyau: Option<fn() -> !>,
}

